version: '3'

services:
  mypo:
    build: ./
    volumes:
      - .:/app
    working_dir: /app
    environment:
      PYPI_API_TOKEN: ${PYPI_API_TOKEN}
    ports:
      - 8888:8888
    command: ['bash', '/app/tutorial/start.sh']