version: '3'

services:
  mypo:
    image: 'ghcr.io/sonesuke/mypo:latest'
    volumes:
      - '.:/app:delegated'
    working_dir: /app
    environment:
      PYPI_API_TOKEN: ${PYPI_API_TOKEN}
      JUPYTER_TOKEN: ${JUPYTER_TOKEN:-1111}
    ports:
      - 8888:8888
    command: ['bash', '/app/scripts/start.sh']