
[tool.poetry]
name = "mypo"
version = "0.0.19"
description = ""
authors = [
    "sonesuke <iamsonesuke@gmail.com>"
]

license = "MIT"
readme = "README.md"

repository = "https://github.com/sonesuke/mypo"
homepage = "https://github.com/sonesuke/mypo"

[tool.poetry.dependencies]
python = "^3.9.1"
pandas = "^1.2.2"
yfinance = "^0.1.55"
numpy = "^1.20.1"
scikit-learn = "^0.24.1"
scipy = "^1.6.0"
mypy = "^0.812"
isort = "^5.7.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-flake8 = "^1.0.4"
ipython = "^7.13.0"
jupyter = "^1.0.0"
pytest-mypy = "^0.8.0"
mypy = "^0.812"
black = "^20.8b1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
line-length = 120

[tool.pytest.ini_options]
addopts = "--flake8 --mypy"
flake8-max-line-length = 120
filterwarnings = [
    "error",
    "ignore::UserWarning"
]
