name: pull-request

on:
  push:
    tags:
      - 'docs.[0-9]+'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: deploy documentation
        shell: bash
        run: docker-compose run mypo bash /app/scripts/docs.sh

