name: pull-request

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Test
        shell: bash
        run: docker-compose run mypo bash /app/scripts/test.sh

